init:
  - ps: if ($env:APPVEYOR_REPO_TAG -eq "true") { $env:TAG_VERSION = "$env:APPVEYOR_REPO_TAG_NAME.$env:APPVEYOR_BUILD_NUMBER" } else { $env:TAG_VERSION = "v1.5.0.$env:APPVEYOR_BUILD_NUMBER-alpha" }
  - ps: $env:TAG_VERSION = $env:TAG_VERSION -replace 'v',''
  - ps: Write-Host "Setting version to '$env:TAG_VERSION'"
  - ps: Update-AppveyorBuild -Version "$env:TAG_VERSION"

environment:
  LMVTestAgentUsername: SecretAgentTest Resident
  LMVTestAgentPassword:
    secure: bOoXrGfLiHjZlCG1tJ+nDQ==

  matrix:
  - job_name: Windows build
    appveyor_build_worker_image: Visual Studio 2019
    configuration: Release
  - job_name: Linux build
    appveyor_build_worker_image: Ubuntu1804
    configuration: ReleaseNoGui



pull_requests:
  do_not_increment_build_number: false

nuget:
  disable_publish_on_pr: true

build:
  project: LibreMetaverse.sln
  parallel: true
  verbosity: minimal
  publish_nuget: true
  publish_nuget_symbols: false

cache:
  - packages -> **\packages.config
  - '%LocalAppData%\NuGet\Cache'

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'

before_build:
  - nuget restore LibreMetaverse.sln

deploy:
  - provider: NuGet
    name: nuget_release
    api_key:
      secure: WAEp9wQu4tWKiMdcfog7FWpzk7rPou8flMCYlmYy3mZ+thKwmG1ht4o4mmEE6ZLs
    skip_symbols: true
    artifact: /.*LibreMetaverse.*\.nupkg/
    on:
      job_name: Windows build
  - provider: GitHub
    name: github_releases
    description: Release v$(appveyor_build_version)
    tag: $(appveyor_build_version)
    auth_token:
      secure: NWduXKOpjxTw6TAgzMV9SsBERjq5Qxv49XKbDtu6XQV7GygeQmG1RTKeyxl4zV1A
    skip_symbols: true
    artifact: /.*LibreMetaverse.*\.nupkg/
    draft: false
    prerelease: false
    on:
      job_name: Windows build
      APPVEYOR_REPO_TAG: true
